

%% make ppt-slide
%% PAIRWISE PARAMETER
% doc      either 'new' or 'add' to append (default: 'new')
% file     pptfile-name (fullpath)
% bgcol    backgroundcolor;  default [1 1 1]% [1.0000    0.9490    0.8667]; 
% text     text to show  (as cell or string) ; default: {'haus' 'maus'}; 
% fs       fontsize (default: 50)
% 
%% examples
% makePPTslide('doc','new','file',fullfile(pwd,'dum3'),'fs',70,'text','HalloWorld','bgcol',[1 1 .5 ])
% makePPTslide('doc','new','file',fullfile(pwd,'dum3'),'fs',70,'text',{'123' 'hallo'},'bgcol',[ 0.8706    0.9216    0.9804])
% makePPTslide('doc','new','file',fullfile(pwd,'dum2'),'fs',70,'text','HalloWorld')
% add a 2nd slide
% makePPTslide('doc','add','file',fullfile(pwd,'dum2'),'fs',50,'text','this is slide-2')
%


function makePPTslide(varargin)

p=cell2struct(varargin(2:2:end),varargin(1:2:end),2);
p0.doc     ='new'  ;% either 'new' or 'add' to append
p0.file   =fullfile(pwd,'dum'); %pptfile
p0.bgcol  =[1 1 1]; %backgroundcolor
p0.text   ={'haus' 'maus'}; %text to show
p0.fs     =50; %fontsize

warning off;
p=catstruct(p0,p);
p.text=cellstr(p.text);

%% ===============[ppt path]================================
thispa=pwd; %remember current dir
[paPPT pptfile ]=fileparts(p.file);
if isempty(paPPT); 
    paPPT=pwd;
end

cd(paPPT);%go to  to ppt-dir
%% ===============[Start new presentation]================================
%% 
isOpen  = exportToPPTX();
if ~isempty(isOpen)   % If PowerPoint already started, then close first and then open a new one
    exportToPPTX('close');
end
% try
%     %evalc('system(''taskkill /f /im powerpnt.exe'')');
% end
%% =======new PPT/add to ppt ========================================

if strcmp(p.doc,'add') && exist([pptfile,'.pptx'])
    exportToPPTX('open',[pptfile,'.pptx'])
else
    exportToPPTX('new','Dimensions',[12 6], ...
        'Title','Example Presentation', ...
        'Author','MatLab', ...
        'Subject','Automatically generated PPTX file', ...
        'Comments','This file has been automatically generated by exportToPPTX');
end
%% ===============================================


% exportToPPTX('new');
exportToPPTX('addslide','BackgroundColor',p.bgcol)
% exportToPPTX('addtext','Hello World!');
exportToPPTX('addtext',strjoin(p.text,char(10)),'FontSize',p.fs,'HorizontalAlignment','center',...
    'VerticalAlignment','middle');
exportToPPTX('saveandclose',pptfile);


% ==============================================
%%   back to calling dir
% ===============================================
cd(thispa);