
% merge xls-tables to single ppt
% xls2ppt(pabase,flt,sheetnum,pptfile)
% flt='^.*.xlsx'
% pabase=pwd
% sheetnum=2
% pptfile  =fullfile(pabase,'test3.pptx');
% xls2ppt(pabase,flt,sheetnum,pptfile)
% xls2ppt(pabase,'^.*.xlsx',2,fullfile(pwd,'brainvol.pptx'))
    
function xls2ppt(pabase,flt,sheetnum,pptfile)
% ==============================================
%%
% ===============================================
if 0
    %     flt='^.*.xlsx'
    %     pabase=pwd
    %     sheetnum=2
    %     pptfile  =fullfile(pabase,'test3.pptx');
    % xls2ppt(pabase,flt,sheetnum,pptfile)
    xls2ppt(pwd,'^.*.xlsx',2,fullfile(pwd,'brainvol.pptx'))
end

% pabase='H:\Daten-2\Imaging\AG_Mueller_Mainz\stat_brainvol\result';
if iscell(pabase) && size(pabase,1)>1
    files=pabase;
else
    [files]  = spm_select('FPList',pabase,flt); files=cellstr(files);
end
% pptfile  =fullfile(pabase,'test2.pptx');
% sheetnum=2
%% ===============================================
thisdir=pwd;

s.bgcol=[1 1 1];
for i=1:length(files)
    try
    cd(fileparts(pptfile));
    fi=files{i};
    [~,sheetnames]=xlsfinfo(fi);
    [~,~,a]=xlsread(fi,sheetnum);
    if size(a,1)>200
        a=a(1:200,:);
    end
    
    
    % ===============================================
    [pa , fname, ext]=fileparts(fi);
    [pa1, subdir, ]=fileparts(pa);
    [~, subdir2, ]=fileparts(pa1);
    info={
        ['file: '    [  fname ext ]]
        ['dir : '    [  subdir    ]]
        ['dirUp : '  [  subdir2   ]]
        ['sheet: '  sheetnames{sheetnum} ]
        };
    
    
    
    % ===============================================
    
    isOpen  = exportToPPTX();
    if ~isempty(isOpen),
        % If PowerPoint already started, then close first and then open a new one
        exportToPPTX('close');
    end
    
    % =======new PPT/add to ppt ========================================
    % if strcmp(s.doc,'add') && exist([pptfile,'.pptx'])
    %     exportToPPTX('open',[pptfile,'.pptx'])
    % else
    % ===============================================
    
    
    if i==1
    exportToPPTX('new','Dimensions',[12 6], ...
        'Title','Example Presentation', ...
        'Author','MatLab', ...
        'Subject','Automatically generated PPTX file', ...
        'Comments','This file has been automatically generated by exportToPPTX');
    else
     exportToPPTX('open',[pptfile]);
    end
         
    % cd(paPPT);
    slideNum = exportToPPTX('addslide','BackgroundColor',s.bgcol);
    fprintf('Added slide %d\n',slideNum);
    % exportToPPTX('addpicture',figH);
    % exportToPPTX('addtext',lb.String{lb.Value});
    exportToPPTX('addtext',strjoin(info,char(10)),'FontSize',10,...
        'Position',[0 0 3 3  ]);
    
    m=plog([],a,0,[  fname ext ],'d=5;al=1');
    % m=strjoin(m,char(10))
    
    exportToPPTX('addtext',strjoin(m,char(10)),'FontSize',7,...
        'FontName','Courier New','Position',[0 1 15 3  ])
    
    
    %exportToPPTX('addnote',sprintf('Notes data: slide number %d',slideNum));
    exportToPPTX('addnote',['source: '  pwd ]);
    % Rotate mesh on each slide
    %     view(18*islide,18*islide);
    
    
    % close(figH)
    % Check current presentation
    
    fileStats   = exportToPPTX('query');
    newFile = exportToPPTX('saveandclose',pptfile);
    catch
        disp(lasterr)
        disp(['error: maybe excel-file/ppt-file open?'  ])
        rethrow(lasterr);
    end
    
end
fprintf('New file has been saved: <a href="matlab:open(''%s'')">%s</a>\n',newFile,newFile);

cd(thisdir);











